name: Run Tests on Commit

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.jobs
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test